language: python

branches:
  only:
    - master

install:
- pip install mkdocs
- pip install mkdocs-material

script:
  - git clean -f -d -x
  - mkdocs build
  - mv site/* .

deploy:
  provider: pages
  skip_cleanup: true
  target_branch: gh-pages
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
